Quickstart
----------

.. toctree::
    :maxdepth: 2

    quickstart

Tutorial
--------

.. toctree::
    :maxdepth: 2

API Reference
-------------

If you are looking for information on a specific function, class or
method, this part of the documentation is for you.

.. toctree::
    :maxdepth: 2

    api

Utilities
---------

Refernce for various utility modules in circleci.py

.. toctree::
    :maxdepth: 2

    util

Developer Documentation
-----------------------

.. toctree::
    :maxdepth: 2

    dev

Changelog
---------

.. toctree::
    :maxdepth: 3

    changelog

Attribution
-----------

* circleci.py relies on the wonderful `requests <http://docs.python-requests.org/en/master/>`_ library for all HTTP requests. This library is licensed under the `Apache License, Version 2.0 <http://www.apache.org/licenses/LICENSE-2.0>`_.
* A majority of the API doc strings are adapted from the official `CircleCI API documentation <https://circleci.com/docs/api/v1-reference/>`_ which is licensed under a `Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License <http://creativecommons.org/licenses/by-nc-sa/4.0/>`_.
